--
-- Script was generated by Devart dbForge Studio 2019 for PostgreSQL, Version 2.0.111.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 29/03/2022 8:56:33 AM
-- Server version: PostgreSQL 9.6.14 on x86_64-pc-linux-gnu (Debian 9.6.14-1.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
--

